---
title: "&#32;"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
carob_path = "../../../carob/"

data_path = file.path(carob_path, "data/compiled")
data_path2 = file.path(carob_path, "data")
  
library(kableExtra)
```

```{r groups, echo=FALSE}
ff <- list.files(data_path, pattern=".csv$", full=TRUE)
ff <- ff[!grepl("_terms", ff)]
f <- grep(ff, pattern="_metadata.csv$", value=TRUE)

groups <- gsub("_metadata.csv$", "", basename(f))
groups <- gsub("^carob_", "", groups)

d <- lapply(f, read.csv)
d <- do.call(carobiner::bindr, d)


get_tab <- function(d, var) {
	n <- d[[var]]
	n <- strsplit(n, ";")
	n <- lapply(1:length(n), \(i) {
		if (length(n[[i]])== 0) return(NULL)
		data.frame(id=i, p=trimws(unlist(n[[i]])))
	})
	p <- do.call(rbind, n)
	tab <- as.data.frame(table(p$p))
	colnames(tab) <- c("name", "datasets")
	tab 
}

#pp <- sapply(1:length(d), \(i) {
#			d[[i]][["authors"]]
#			}
#		) |> unlist()


get_authors <- function(d) {
	n <- d[["authors"]]
	n <- strsplit(n, ";")
	n <- lapply(1:length(n), \(i) {
		if (length(n[[i]])== 0) return(NULL)
		data.frame(id=i, p=unlist(n[[i]]))
	})
	p <- do.call(rbind, n)
	p$p <- gsub(",", ", ", p$p)
	p$p <- gsub(",  ", ", ", p$p)
	p$p[grep("applicable", p$p, TRUE)] <- ""
	p$p <- gsub("Andrew J. McDonald", "McDonald, Andrew", p$p) 
	p$p <- gsub("Sherpa R. Sonam", "Sherpa, Sonam", p$p) 
	p$p <- gsub("Abubakar H.Inuwa", "Abubakar H. Inuwa", p$p) 
	p$p[grepl("Wortmann", p$p)] <- "Wortmann, Charles S."
	p$p <- gsub("Wiredu Alexanda Nimo", "Wiredu, Alexanda Nimo", p$p) 
	p$p <- gsub("Bolo, Peter$", "Bolo, Peter Omondi", p$p) 
	p$p <- gsub("Dorado, Hugo A.", "Dorado Betancourt, Hugo A.", p$p) 
	p$p <- gsub("Eyzaguire, Raul", "Eyzaguirre, Raul", p$p) 
	p$p <- gsub("Dicko, M. K.|Dicko, Mohamed", "Dicko, Mohammed K.", p$p) 
	p$p <- gsub("Joon, Rajeev", "Joon, K Rajeev", p$p) 
	p$p <- gsub("Pundir, Ajay", "Pundir, K Ajay", p$p) 
	p$p <- gsub("Lilongwe University of Agriculture & Natural Resources (LUANAR)", "Lilongwe University of Agriculture & Natural Resources", p$p) 
	p$p <- gsub("Nabahungu, L$|Nabahungu, Leon N.", "Nabahungu, Léon N.", p$p) 
	p$p <- gsub("Nkonde, D.$", "Nkonde, Davy", p$p) 
	p$p <- gsub("Rojas-Cruz, Juan Manuel", "Rojas Cruz, Juan Manuel", p$p) 
	p$p <- gsub("Saldivia-Tejeda, Abel", "Saldivia Tejeda, Abel", p$p) 
	
	nms1 <- c("Sherpa Sonam", "Poonia Shishpal", "Kumar Sunil", "Sharma Sachin", "Ajay Anurag", "Wu William", "Singh Balwinder", "McDonald Andrew", "Hood-Nowotny Rebbeca", "Majaliwa Jackson", "Tumuhairwe John-Baptist", "Quispe Katherine", "Okoth John",  "Kyei-Boahen Stephen")
	nms2 <- gsub(" ", ", ", nms1)
	for (i in 1:length(nms1)) p$p <- gsub(nms1[i], nms2[i], p$p)

	i <- grepl(",|CRS|IER|ICRAF|ABC|ICRISAT|SARI|IITA|IRRI|ISRIC|CIMMYT|TLC|University|IWIN|ARI|Program|ILRI|Davis", p$p)
	n <- strsplit(p$p[!i], " \\s*(?=[^ ]+$)", perl=TRUE)
	p$p[!i] <- sapply(n, \(i) paste0(rev(i), collapse=", "))
	p$p <- gsub("-, ", "", p$p) # "-, RHoMIS"
	p$p <- gsub("Anurag, Ajay", "Ajay, Anurag", p$p)
	p$p <- gsub("Sila, Andrew Musili", "Sila, Andrew", p$p) 
	p$p <- gsub("Sileshi, Gudeta W$", "Sileshi, Gudeta W.", p$p) 
	p$p <- gsub("Talabi, A. O.|Talabi, O.A.", "Talabi, A.O.", p$p) 
	p$p <- gsub("Tor Gunnar", "Tor-Gunnar", p$p) 
	p$p <- gsub("Winowiecki, Leigh$", "Winowiecki, Leigh Ann", p$p) 
	p$p <- gsub("Balemi, T$", "Balemi, Tesfaye", p$p)
	p$p <- gsub("Cyamweshi, A. R.", "Cyamweshi, Athanase R.", p$p)
	p$p <- gsub("H, Sudini", "Sudini, H", p$p) 
	p$p <- gsub("))", ")", p$p)
	p$p[p$p == "World Agroforestry (ICRAF)"] <- "World Agroforestry Center (ICRAF)"
	p$p <- gsub("Zambian Agriculture Research Institute", "Zambia Agricultural Research Institute", p$p)
		
	p <- p[!grepl("ABC|CIAT|ILRI|IFPRI|IRRI|IWMI|CIMMYT|ICRISAT|IITA|ICRAF|TARI|University of California|MSU|Ministry of Food and Agriculture (MOFA), Republic of Ghana|SARI|ZARI|CRS|TLC", p$p), ]
	p$p <- gsub("  ", " ", p$p)
	p$p <- trimws(p$p)
	p <- p[p$p !="", ]
	p$p <- gsub("H, Nadaf", "Nadaf, H", p$p) 
	p$p <- gsub("P, Latha", "Latha, P", p$p) 
	p$p <- gsub("Rurinda, J$", "Rurinda, Jairos", p$p) 
	p$p <- gsub("Trust, Grassroots", "Grassroots Trust", p$p) 
	
	tab <- as.data.frame(table(p$p))
	colnames(tab) <- c("name", "datasets")
	tab$alpha <- toupper(substr(tab$name, 1, 1))
	tab
}


cartab <- get_tab(d, "carob_contributor")
autab <- get_authors(d)
intab <- get_tab(d, "data_institute")



inst <- carobiner::accepted_values("institute")
intab <- merge(intab, inst, by="name", all.x=TRUE)
intab$name <- paste0('<a href="https://', intab$URL, '">', intab$name, "</a>")

```

### Script authors

```{r catable, echo=FALSE}
cartab[,2][cartab[,2] > 250] <- "250+"
out = paste0(paste0(cartab[,1], " (", cartab[,2], ")"), collapse="; ")
#kableExtra::kbl(cartab) |> kable_classic(full_width = FALSE) |>
#   kable_styling(bootstrap_options = c("striped", "hover"))
```
`r out`

### Dataset institutes

```{r instable, echo=FALSE}
out = paste0(paste0(intab[,1], " (", intab[,2], ")"), collapse="; ")
#kableExtra::kbl(intab) |> kable_classic(full_width = FALSE) |>
#   kable_styling(bootstrap_options = c("striped", "hover"))
```
`r out`

### Dataset authors

```{r autable, echo=FALSE}
out <- NULL
for (letter in unique(autab$alpha)) {
  tab <- autab[autab$alpha == letter, , drop=FALSE]
  out <- paste0(out, "\n\n", paste0(tab[,1], " (", tab[,2], ")", collapse="; "), "\n\n")
}
#DT::datatable(autab, escape=FALSE, rownames=FALSE)
```

`r out`


<br>
