---
title: "&#32;"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
carob_path = "../../../carob/"
data_path = file.path(carob_path, "data/compiled")
data_path2 = file.path(carob_path, "data")
  
library(kableExtra)
library(terra)
library(geodata)
library(leaflet)
```

*Carob* aggregates data sets into groups. Below is a table with the current groups and the number of datasets and records in each group. We also show these numbers for the datasets that have a Creative Commons (CC) license.

```{r groups, echo=FALSE}
ff <- list.files(data_path, pattern=".csv$", full=TRUE)
ff <- ff[!grepl("carob_terms", ff)]
f <- grep(ff, pattern="_metadata.csv$", value=TRUE)

groups <- gsub("_metadata.csv$", "", basename(f))
groups <- gsub("^carob-", "", groups)

d <- lapply(f, read.csv)
n1 <- sapply(d, nrow)
n2 <- sapply(d, \(i) sum(grepl("CC", i$license)))

f <- grep(ff, pattern="_metadata", invert=TRUE, value=TRUE)
fall <- grep(f, pattern="-CC", invert=TRUE, value=TRUE)
fcc <- grep(f, pattern="-CC", value=TRUE)

dd <- lapply(fall, read.csv)
nr1 <- sapply(dd, nrow)
ddcc <- lapply(fcc, read.csv)
nr2 <- sapply(ddcc, nrow)
grp2 <- gsub("-CC.csv$", "", basename(fcc))
grp2 <- gsub("^carob-", "", grp2)

d <- data.frame(Group=grp2, `CC-Records`=nr2, check.names=FALSE)

x <- data.frame(Group=groups, Datasets=n1, Records=nr1, `CC-Datasets`=n2, check.names=FALSE)
x <- merge(x, d, by="Group", all.x=TRUE)
x[is.na(x)] <- 0

kableExtra::kbl(x) |> kable_classic(full_width = FALSE) |>
   kable_styling(bootstrap_options = c("striped", "hover"))
```

<br>

Here is a map with all locations for which we have at least one observation.

```{r map, echo=FALSE, fig.height=3.5}
w <- world(path=data_path2)
geo <- do.call(rbind, lapply(1:length(dd), \(i) data.frame(Group=groups[i], dd[[i]][, c("country", "longitude", "latitude")]))) |> unique()
geo <- na.omit(geo)
geo <- geo[geo$longitude > -180, ]
geo <- geo[geo$latitude < 60, ]
v <- vect(geo, c("longitude", "latitude"), crs="+proj=longlat")
e <- extract(w, v)
v$NAME_0 <- e$NAME_0
v <- v[!is.na(v$NAME_0), ]
v <- v[v$NAME_0 == v$country, ]

plot(w, col=gray(.95), background="azure", ylim=c(-60,80), lwd=1.25)
plot(v, "Group", col=colorRampPalette(c("red", "orange", "blue"))(6), cex=.4, pch=1, add=TRUE, legend=TRUE, plg=list(x="bottomleft"))
lines(w, col="light gray", lwd=.5)
``` 

Interactive 

```{r plet, echo=FALSE, fig.height=4}
plet(v, "Group", split=TRUE, alpha=.2, clusterOptions=markerClusterOptions())
```
